package vista;

import Modelo.Instalacion;
import Persistencia.InstalacionData;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class frmInstalacionesLibres extends javax.swing.JInternalFrame {

    private InstalacionData instalacionData;

    public frmInstalacionesLibres() {
        initComponents();
        instalacionData = new InstalacionData(); // si tu constructor requiere Connection, pasalo
        cargarFranjas();
        configurarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInstal = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        comboBoxFranjas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);

        tablaInstal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaInstal);

        jLabel1.setFont(new java.awt.Font("Century", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Instalaciones libres hoy");

        comboBoxFranjas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxFranjas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboBoxFranjas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxFranjasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Seleccione una franja horaria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(comboBoxFranjas, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(274, 274, 274))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(comboBoxFranjas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxFranjasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFranjasActionPerformed
        cargarInstalacionesLibres();
    }//GEN-LAST:event_comboBoxFranjasActionPerformed

    private void cargarFranjas() {
        comboBoxFranjas.removeAllItems();
        comboBoxFranjas.addItem("09-11");
        comboBoxFranjas.addItem("11-13");
        comboBoxFranjas.addItem("13-15");
        comboBoxFranjas.addItem("15-17");
        comboBoxFranjas.addItem("17-19");
    }

    private void configurarTabla() {
        String[] columnas = {"Código", "Nombre", "Detalle", "Precio 30m"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        tablaInstal.setModel(modelo);
    }

    private void cargarInstalacionesLibres() {

        if (comboBoxFranjas.getSelectedItem() == null) {
            return;
        }

        String franja = comboBoxFranjas.getSelectedItem().toString(); // ej. "13-15"
        String[] partes = franja.split("-");

        int hInicio = Integer.parseInt(partes[0]);
        int hFin = Integer.parseInt(partes[1]);

        LocalDate hoy = LocalDate.now();
        LocalDateTime inicio = hoy.atTime(hInicio, 0);
        LocalDateTime fin = hoy.atTime(hFin, 0);
        System.out.println("horarios: inicio "+inicio+" y fin "+fin);
        List<Instalacion> libres = instalacionData.getInstalacionesLibres(inicio, fin);
        System.out.println("Libres: "+libres);
        actualizarTabla(libres);
    }

    private void actualizarTabla(List<Instalacion> lista) {
        DefaultTableModel modelo = (DefaultTableModel) tablaInstal.getModel();
        modelo.setRowCount(0); //aca limpio la tabla
        System.out.println("Lista de instalaciones: "+lista);
        for (Instalacion i : lista) {
            modelo.addRow(new Object[]{
                i.getCodInstal(),
                i.getNombre(),
                i.getdetalledeuso(),
                i.getPrecio30m()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxFranjas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaInstal;
    // End of variables declaration//GEN-END:variables
}
