package vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author thefl
 */
public class frmMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName());

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {
        initComponents();
        this.setTitle("Menú Principal - Spa Entre Dedos");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jfrmCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jfrmMasajista = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jfrmConsultorio = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jfrmTratamiento = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jfrmInstalacion = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jSalir = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        jMenu2.setText("Cliente");

        jfrmCliente.setText("frmCliente");
        jfrmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jfrmCliente);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Masajista");

        jfrmMasajista.setText("frmMasajista");
        jfrmMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmMasajistaActionPerformed(evt);
            }
        });
        jMenu3.add(jfrmMasajista);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultorio ");

        jfrmConsultorio.setText("frmConsultorio ");
        jfrmConsultorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmConsultorioActionPerformed(evt);
            }
        });
        jMenu4.add(jfrmConsultorio);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Tratamiento ");

        jfrmTratamiento.setText("frmTratamiento");
        jfrmTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmTratamientoActionPerformed(evt);
            }
        });
        jMenu5.add(jfrmTratamiento);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Instalacion ");

        jfrmInstalacion.setText("frmInstalacion ");
        jfrmInstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmInstalacionActionPerformed(evt);
            }
        });
        jMenu6.add(jfrmInstalacion);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Sesion ");

        jMenuItem2.setText("Turnos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Dia de Spa");

        jMenuItem1.setText("Spa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem1);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Salir ");

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        jMenu9.add(jSalir);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfrmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmClienteActionPerformed
         frmCliente ventana = new frmCliente();
        jDesktopPane1.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_jfrmClienteActionPerformed

    private void jfrmMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmMasajistaActionPerformed
        frmMasajista ventana = new frmMasajista();
        jDesktopPane1.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_jfrmMasajistaActionPerformed

    private void jfrmConsultorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmConsultorioActionPerformed
       frmConsultorio ventana = new frmConsultorio();
        jDesktopPane1.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_jfrmConsultorioActionPerformed

    private void jfrmTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmTratamientoActionPerformed
       frmTratamiento ventana = new frmTratamiento();
        jDesktopPane1.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_jfrmTratamientoActionPerformed

    private void jfrmInstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmInstalacionActionPerformed
        frmInstalacion ventana = new frmInstalacion();
        jDesktopPane1.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_jfrmInstalacionActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
          System.exit(0);
    }//GEN-LAST:event_jSalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmDiaDeSpa ventana = new FrmDiaDeSpa();
     jDesktopPane1.add(ventana);
     ventana.setVisible(true);
     ventana.toFront();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmSesion ventana = new FrmSesion();
     jDesktopPane1.add(ventana);
     ventana.setVisible(true);
     ventana.toFront();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jSalir;
    private javax.swing.JMenuItem jfrmCliente;
    private javax.swing.JMenuItem jfrmConsultorio;
    private javax.swing.JMenuItem jfrmInstalacion;
    private javax.swing.JMenuItem jfrmMasajista;
    private javax.swing.JMenuItem jfrmTratamiento;
    // End of variables declaration//GEN-END:variables
}
