package vista;

import javax.swing.JInternalFrame;
import javax.swing.UIManager;

public class frmMenuPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName());

    public frmMenuPrincipal() {
        initComponents();
        this.setTitle("Menú Principal - Spa Entre Dedos");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jfrmCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jfrmMasajista = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jfrmConsultorio = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jfrmTratamiento = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jfrmInstalacion = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jSalir = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setMinimumSize(new java.awt.Dimension(1024, 768));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        jMenu2.setText("Cliente");

        jfrmCliente.setText("frmCliente");
        jfrmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jfrmCliente);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Masajista");

        jfrmMasajista.setText("Masajista");
        jfrmMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmMasajistaActionPerformed(evt);
            }
        });
        jMenu3.add(jfrmMasajista);

        jMenuItem6.setText("Especialidad");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem5.setText("Libres");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultorio ");

        jfrmConsultorio.setText("frmConsultorio ");
        jfrmConsultorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmConsultorioActionPerformed(evt);
            }
        });
        jMenu4.add(jfrmConsultorio);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Tratamiento ");

        jfrmTratamiento.setText("frmTratamiento");
        jfrmTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmTratamientoActionPerformed(evt);
            }
        });
        jMenu5.add(jfrmTratamiento);

        jMenuItem7.setText("Tratamiento segun Tipo");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuItem3.setText("Tratamientos Solicitados");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Instalacion ");

        jfrmInstalacion.setText("frmInstalacion ");
        jfrmInstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfrmInstalacionActionPerformed(evt);
            }
        });
        jMenu6.add(jfrmInstalacion);

        jMenuItem4.setText("Instalaciones Solicitadas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Sesion ");

        jMenuItem2.setText("Turnos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Dia de Spa");

        jMenuItem1.setText("Spa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem1);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Salir ");

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        jMenu9.add(jSalir);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfrmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmClienteActionPerformed
        frmCliente ventana = new frmCliente();
        jDesktopPane1.add(ventana);
        ventana.setVisible(true);
        centrarVentana(ventana);
        mostrarVentana(new frmCliente());
    }//GEN-LAST:event_jfrmClienteActionPerformed

    private void jfrmMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmMasajistaActionPerformed
        frmMasajista ventana = new frmMasajista();
        jDesktopPane1.add(ventana);
        ventana.setVisible(true);
        centrarVentana(ventana);
        mostrarVentana(new frmMasajista());
    }//GEN-LAST:event_jfrmMasajistaActionPerformed

    private void jfrmConsultorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmConsultorioActionPerformed
        frmConsultorio ventana = new frmConsultorio();
        jDesktopPane1.add(ventana);
        ventana.setVisible(true);
        centrarVentana(ventana);
        mostrarVentana(new frmConsultorio());
    }//GEN-LAST:event_jfrmConsultorioActionPerformed

    private void jfrmTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmTratamientoActionPerformed
        frmTratamiento ventana = new frmTratamiento();
        jDesktopPane1.add(ventana);
        ventana.setVisible(true);
        centrarVentana(ventana);
        mostrarVentana(new frmTratamiento());
    }//GEN-LAST:event_jfrmTratamientoActionPerformed

    private void jfrmInstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfrmInstalacionActionPerformed
        frmInstalacion ventana = new frmInstalacion();
        jDesktopPane1.add(ventana);
        ventana.setVisible(true);
        centrarVentana(ventana);
        mostrarVentana(new frmInstalacion());
    }//GEN-LAST:event_jfrmInstalacionActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jSalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmDiaDeSpa ventana = new FrmDiaDeSpa();
        jDesktopPane1.add(ventana);
        ventana.setVisible(true);
        ventana.toFront();
        centrarVentana(ventana);
        mostrarVentana(new FrmDiaDeSpa());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmSesion ventana = new FrmSesion();
        jDesktopPane1.add(ventana);
        ventana.setVisible(true);
        ventana.toFront();
        centrarVentana(ventana);
        mostrarVentana(new FrmSesion());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        frmTratamientosMasSesionados ventana = new frmTratamientosMasSesionados();
        jDesktopPane1.add(ventana);
        ventana.setVisible(true);
        ventana.toFront();
        centrarVentana(ventana);
        mostrarVentana(new frmTratamientosMasSesionados());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        frmMasajistasLibres ventana = new frmMasajistasLibres();
        jDesktopPane1.add(ventana);
        ventana.setVisible(true);
        ventana.toFront();
        centrarVentana(ventana);
        mostrarVentana(new frmMasajistasLibres());
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FrmInstalacionesMasSolicitadas ventana = new FrmInstalacionesMasSolicitadas();
        jDesktopPane1.add(ventana);
        ventana.setVisible(true);
        ventana.toFront();
        centrarVentana(ventana);
        mostrarVentana(new FrmInstalacionesMasSolicitadas());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        frmMasajistaEspecialidad ventana = new frmMasajistaEspecialidad();
        jDesktopPane1.add(ventana);
        ventana.setVisible(true);
        ventana.toFront();
        centrarVentana(ventana);
        mostrarVentana(new frmMasajistaEspecialidad());
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        frmTratamientosegunTipo ventana = new frmTratamientosegunTipo();
        jDesktopPane1.add(ventana);
        ventana.setVisible(true);
        ventana.toFront();
        centrarVentana(ventana);
        mostrarVentana(new frmTratamientosegunTipo());
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void mostrarVentana(JInternalFrame frame) {
    for (JInternalFrame ventana : jDesktopPane1.getAllFrames()) {
        ventana.dispose();
    }

    jDesktopPane1.add(frame);
    frame.setVisible(true);
    centrarVentana(frame);
}
    public void centrarVentana(JInternalFrame frame) {
    int x = (jDesktopPane1.getWidth() - frame.getWidth()) / 2;
    int y = (jDesktopPane1.getHeight() - frame.getHeight()) / 2;
    frame.setLocation(x, y);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        // Look & Feel moderno
        try {
            javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());

            // Bordes redondeados
            UIManager.put("Component.arc", 20);
            UIManager.put("TextComponent.arc", 20);
            UIManager.put("Button.arc", 20);
            UIManager.put("ComboBox.arc", 20);
            UIManager.put("CheckBox.arc", 20);
            UIManager.put("Component.innerFocusWidth", 1);
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "No se pudo cargar FlatLaf", ex);
        }

        java.awt.EventQueue.invokeLater(() -> new frmMenuPrincipal().setVisible(true));

        //esto era con Nimbus, pero implementamos flatlaf
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(() -> new frmMenuPrincipal().setVisible(true));*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jSalir;
    private javax.swing.JMenuItem jfrmCliente;
    private javax.swing.JMenuItem jfrmConsultorio;
    private javax.swing.JMenuItem jfrmInstalacion;
    private javax.swing.JMenuItem jfrmMasajista;
    private javax.swing.JMenuItem jfrmTratamiento;
    // End of variables declaration//GEN-END:variables
}
