package vista;

import Modelo.Tratamiento;
import Persistencia.TratamientoData;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.util.Objects;

public class frmTratamientosMasSesionados extends javax.swing.JInternalFrame {

    private TratamientoData tratamientoData = null;
    private DefaultTableModel modelo = new DefaultTableModel();

    public frmTratamientosMasSesionados() {
        initComponents();
        this.getContentPane().setBackground(new Color(245, 242, 232));
        try {
            tratamientoData = new TratamientoData();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo crear TratamientoData.\n" + ex.getMessage(),
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

        jTable1.setModel(modelo);
        armarTabla();
        centrarColumnas();
    }

    private void armarTabla() {
        modelo.setRowCount(0);
        modelo.setColumnCount(0);

        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Sesiones");
    }

    private void cargarTabla() {
        modelo.setRowCount(0);

        if (Objects.isNull(tratamientoData)) {
            JOptionPane.showMessageDialog(this, "No está disponible TratamientoData.");
            return;
        }

        try {
            List<Tratamiento> lista = tratamientoData.listarTratamientosMasSesionados();

            if (Objects.isNull(lista) || lista.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay datos para mostrar.");
                return;
            }

            for (Tratamiento t : lista) {
                if (Objects.nonNull(t)) {
                    modelo.addRow(new Object[]{
                        t.getCodTratam(),
                        t.getNombre(),
                        t.getCantidadSesiones()
                    });
                }
            }
            centrarColumnas();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar tabla: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel1.setText("Tratamientos Mas Sesionados");

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setText("Cargar Tratamientos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tratamiento", "Cantidad de Sesiones"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cargarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void centrarColumnas() {
        javax.swing.table.DefaultTableCellRenderer centerRenderer
                = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
